=== alicedubrovskaya/JavaST_2020_September/task10xml/src/main/resources/medicines.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/xmlparser"
        xmlns:tns="http://www.training.by/xmlparser"
        elementFormDefault="qualified">

    <!--Medicines-->
    <element name="medicines">
        <complexType>
            <sequence>
                <element name="medicine"
                         type="tns:Medicine"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <!--Medicine-->
    <complexType name="Medicine">
        <sequence>
            <element name="name" type="tns:Name"/>
            <element name="pharm" type="tns:Name"/>
            <element name="group" type="tns:Group"/>
            <element name="analog" type="tns:Name"/>
            <element name="versions" type="tns:Versions"/>
        </sequence>
    </complexType>

    <!--Name-->
    <simpleType name="Name">
        <restriction base="string">
            <pattern value="[A-ZА-Я]([a-zA-Zа-яА-я0-9-]\s?)+"/>
        </restriction>
    </simpleType>


    <!--Group-->
    <simpleType name="Group">
        <restriction base="string">
            <!--Антибиотики-->
            <enumeration value="antibiotics"/>
            <!--Антисептики-->
            <enumeration value="antiseptics"/>
            <!--Противовирусные-->
            <enumeration value="antiviral"/>
            <!--Антидеперссанты-->
            <enumeration value="antidepressants"/>
            <!--Болеутоляющие-->
            <enumeration value="analgetics"/>
            <!--Витамины-->
            <enumeration value="vitamins"/>
        </restriction>
    </simpleType>

    <!--Versions-->
    <complexType name="Versions">
        <sequence>
            <element name="version"
                     type="tns:Version"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!--Version-->
    <complexType name="Version">
        <sequence>
            <element name="producer" type="tns:Producer"/>
        </sequence>
        <attribute name="type" type="tns:Consistence" use="required"/>
    </complexType>

    <!--Consistence-->
    <simpleType name="Consistence">
        <restriction base="string">
            <enumeration value="tablets"/>
            <enumeration value="capsules"/>
            <enumeration value="liquid"/>
            <enumeration value="powder"/>
            <enumeration value="drops"/>
            <enumeration value="spray"/>
        </restriction>
    </simpleType>

    <!--Producer-->
    <complexType name="Producer">
        <sequence>
            <element name="certificate" type="tns:Certificate"/>
            <element name="package" type="tns:Package"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
    </complexType>


    <!--Certificate-->
    <complexType name="Certificate">
        <sequence>
            <element name="date-issue" type="date"/>
            <element name="date-expiration" type="date"/>
            <element name="organization" type="tns:Name"/>
        </sequence>
        <attribute name="number" type="string" use="required"/>
    </complexType>

    <!--Package-->
    <complexType name="Package">
        <sequence>
            <element name="quantity" type="int"/>
            <element name="price" type="int"/>
        </sequence>
        <attribute name="type" type="tns:PackageType" use="required"/>
    </complexType>

    <!--PackageType-->
    <simpleType name="PackageType">
        <restriction base="string">
            <!--Флакон-->
            <enumeration value="vial"/>
            <!--Контурная ячейковая-->
            <enumeration value="blister-packaging"/>
            <!--Контурная безъячейковая-->
            <enumeration value="contoure-celless"/>
        </restriction>
    </simpleType>

    <complexType name="Dosage">
        <sequence>
            <element name="quantity" type="int"/>
            <element name="period" type="tns:Period"/>
        </sequence>
    </complexType>

    <!--Period-->
    <simpleType name="Period">
        <restriction base="string">
            <enumeration value="hour"/>
            <enumeration value="day"/>
            <enumeration value="week"/>
            <enumeration value="month"/>
            <enumeration value="year"/>
        </restriction>
    </simpleType>

</schema>

=== alicedubrovskaya/JavaST_2020_September/task10web/src/test/resources/test/data1.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns="http://training.by/medicine"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://training.by/medicine medicines.xsd">

    <medicine>
        <name>Кардиомагнил</name>
        <pharm>Такеда ГмбХ</pharm>
        <group>vitamins</group>
        <analog>Магнекард</analog>
        <analog>Полокард</analog>
        <versions>
            <version type="tablets">
                <producer>
                    <certificate number="ЛСР-009047/20">
                        <issue_date>2008-03-22</issue_date>
                        <organization>Acard</organization>
                    </certificate>
                    <package type="blister_packaging">
                        <quantity>2</quantity>
                        <price>10</price>
                    </package>
                    <dosage>
                        <count>4</count>
                        <period>day</period>
                    </dosage>
                </producer>
            </version>
        </versions>
    </medicine>

</medicines>

=== alicedubrovskaya/JavaST_2020_September/task10xml/src/main/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns="http://www.training.by/xmlparser"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.training.by/xmlparser medicines.xsd">
    <medicine>
        <name>Парацетамол</name>
        <pharm>Ирбитский химфармзавод ОАО</pharm>
        <group>antibiotics</group>
        <analog>Тайленол</analog>
        <versions>
            <version type="tablets">
                <producer>
                    <certificate number="ЛСР-009047/08">
                        <date-issue>2019-03-22</date-issue>
                        <date-expiration>2020-09-22</date-expiration>
                        <organization>BelMedicines</organization>
                    </certificate>
                    <package type="blister-packaging">
                        <quantity>10</quantity>
                        <price>100</price>
                    </package>
                    <dosage>
                        <quantity>3</quantity>
                        <period>day</period>
                    </dosage>
                </producer>
            </version>
        </versions>
    </medicine>

</medicines>

=== alicedubrovskaya/JavaST_2020_September/task10web/src/main/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns="http://training.by/medicine"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://training.by/medicine medicines.xsd">
    <medicine>
        <name>Парацетамол</name>
        <pharm>Ирбитский химфармзавод ОАО</pharm>
        <group>antibiotics</group>
        <analog>Тайленол</analog>
        <analog>Апап</analog>
        <versions>
            <version type="tablets">
                <producer>
                    <limited_certificate number="ЛСР-009047/08">
                        <issue_date>2019-03-22</issue_date>
                        <organization>BelMedicines</organization>
                        <expiration_date>2020-09-22</expiration_date>
                    </limited_certificate>
                    <package type="blister_packaging">
                        <quantity>10</quantity>
                        <price>100</price>
                    </package>
                    <dosage>
                        <count>3</count>
                        <period>day</period>
                    </dosage>
                </producer>
            </version>
            <version type="capsules">
                <producer>
                    <certificate number="ЛСР">
                        <issue_date>2020-03-22</issue_date>
                        <organization>BelMed</organization>
                    </certificate>
                    <package type="vial">
                        <quantity>50</quantity>
                        <price>500</price>
                    </package>
                    <dosage>
                        <count>6</count>
                        <period>week</period>
                    </dosage>
                </producer>
            </version>
        </versions>
    </medicine>

</medicines>

=== alicedubrovskaya/JavaST_2020_September/task10web/src/test/resources/test/data2.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns="http://training.by/medicine"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://training.by/medicine medicines.xsd">

    <medicine>
        <name>Парацетамол</name>
        <pharm>Ирбитский химфармзавод ОАО</pharm>
        <group>antibiotics</group>
        <analog>Тайленол</analog>
        <analog>Апап</analog>
        <versions>
            <version type="tablets">
                <producer>
                    <certificate number="ЛСР-009047/08">
                        <issue_date>2019-03-22</issue_date>
                        <organization>BelMedicines</organization>
                    </certificate>
                    <package type="blister_packaging">
                        <quantity>10</quantity>
                        <price>100</price>
                    </package>
                    <dosage>
                        <count>3</count>
                        <period>day</period>
                    </dosage>
                </producer>
            </version>
        </versions>
    </medicine>

</medicines>

=== alicedubrovskaya/JavaST_2020_September/task10web/src/test/resources/test/data3.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns="http://training.by/medicine"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://training.by/medicine medicines.xsd">

    <medicine>
        <name>Вильпрафенум</name>
        <pharm>Такеда ГмбХ</pharm>
        <group>antibiotics</group>
        <analog>Вильпрафен солютаб</analog>
        <analog>Супракс солютаб</analog>
        <versions>
            <version type="capsules">
                <producer>
                    <certificate number="ЛСР-009047/20">
                        <issue_date>2008-03-22</issue_date>
                        <organization>БЕЛМЕДПРЕПАРАТЫ</organization>
                    </certificate>
                    <package type="contoure_celless">
                        <quantity>2</quantity>
                        <price>250</price>
                    </package>
                    <dosage>
                        <count>1</count>
                        <period>month</period>
                    </dosage>
                </producer>
            </version>
        </versions>
    </medicine>

</medicines>
